# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  xmatters: xmatters/xmatters-orb@1.0
jobs:
  build:
    environment:
      - XM_URL: https://ipugh.xmatters.com/api/integration/1/functions/a67152da-3a0c-4a59-b14c-be93c15aceb8/triggers?apiKey=14444add-0ffe-4bba-b65f-d9d80f5a24f0
    docker:
      # specify the version
      - image: circleci/golang:1.13

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/xMTinkerer/emu-sim
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - xmatters/notify_raw:
          json_payload: >-
            { "properties": { "job": "job name here", "author": "Deon Sanders",
            "something": "value"  }, "recipients": [{ "id": "dsanders" }] }
workflows: 
  build-emusim: 
    jobs: 
      - build